"""
export_report.py - 审查报告导出（Markdown / HTML）
"""

from datetime import datetime
from src.core.ai_reviewer import ReviewReport

SEVERITY_ICONS = {"critical": "🔴", "warning": "🟡", "info": "🔵", "suggestion": "💡"}
SEVERITY_LABELS = {"critical": "CRITICAL", "warning": "WARNING", "info": "INFO", "suggestion": "SUGGESTION"}


def _score_bar(score: int) -> str:
    filled = "█" * score
    empty = "░" * (10 - score)
    return f"`{filled}{empty}` {score}/10"


def report_to_markdown(report: ReviewReport, pr_info: dict = None) -> str:
    """将 ReviewReport 导出为 Markdown 格式。"""
    lines = []
    title = pr_info.get("title", "Code Review") if pr_info else "Code Review"
    lines.append("# AI Code Review Report")
    lines.append("")
    if pr_info:
        lines.append(f"**PR**: {title}")
        lines.append(f"**Author**: {pr_info.get('author', 'N/A')}")
    lines.append(f"**Reviewed**: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append(f"**Overall Score**: {_score_bar(report.overall_score)}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(report.summary)
    lines.append("")

    if report.issues:
        lines.append("---")
        lines.append("")
        lines.append(f"## Issues ({len(report.issues)})")
        lines.append("")
        for issue in report.issues:
            icon = SEVERITY_ICONS.get(issue.severity, "❓")
            loc = f":{issue.line_number}" if issue.line_number else ""
            lines.append(f"### {icon} [{SEVERITY_LABELS.get(issue.severity, issue.severity.upper())}] {issue.title}")
            lines.append("")
            lines.append(f"- **File**: `{issue.file_path}{loc}`")
            lines.append(f"- **Rule**: {issue.rule_id}")
            lines.append(f"- **Description**: {issue.description}")
            lines.append(f"- **Suggestion**: {issue.suggestion}")
            lines.append("")
    else:
        lines.append("✅ No issues found.")
        lines.append("")

    if report.strengths:
        lines.append("---")
        lines.append("")
        lines.append("## Strengths")
        lines.append("")
        for s in report.strengths:
            lines.append(f"- ✅ {s}")
        lines.append("")

    if report.suggestions:
        lines.append("---")
        lines.append("")
        lines.append("## Suggestions")
        lines.append("")
        for s in report.suggestions:
            lines.append(f"- 💡 {s}")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Report generated by AI PR Reviewer (DeepSeek)*")
    return "\n".join(lines)


def report_to_html(report: ReviewReport, pr_info: dict = None) -> str:
    """将 ReviewReport 导出为可打印的 HTML 格式（浏览器可 Ctrl+P 导出 PDF）。"""
    title = pr_info.get("title", "Code Review") if pr_info else "Code Review"
    author = pr_info.get("author", "N/A") if pr_info else "N/A"

    issues_html = ""
    for issue in report.issues:
        icon = SEVERITY_ICONS.get(issue.severity, "❓")
        sev = SEVERITY_LABELS.get(issue.severity, issue.severity.upper())
        loc = f":{issue.line_number}" if issue.line_number else ""
        issues_html += f"""
        <div class="issue {issue.severity}">
            <h3>{icon} <span class="sev-tag {issue.severity}">{sev}</span> {issue.title}</h3>
            <p><strong>File:</strong> <code>{issue.file_path}{loc}</code></p>
            <p><strong>Rule:</strong> {issue.rule_id}</p>
            <p><strong>Description:</strong> {issue.description}</p>
            <p><strong>Suggestion:</strong> {issue.suggestion}</p>
        </div>"""

    strengths = "".join(f"<li>{s}</li>" for s in report.strengths) if report.strengths else "<li>None</li>"
    suggestions = "".join(f"<li>{s}</li>" for s in report.suggestions) if report.suggestions else "<li>None</li>"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>AI Code Review - {title}</title>
<style>
body {{ font-family: -apple-system, sans-serif; max-width: 900px; margin: 0 auto; padding: 2rem; color: #1a1a1a; }}
h1 {{ border-bottom: 2px solid #e0e0e0; padding-bottom: 0.5rem; }}
.meta {{ color: #666; font-size: 0.9rem; }}
.score {{ font-size: 1.3rem; margin: 1rem 0; }}
.score span {{ background: #f0f0f0; padding: 0.3rem 0.8rem; border-radius: 6px; font-weight: bold; }}
.issue {{ border-left: 4px solid #ccc; padding: 0.5rem 1rem; margin: 1rem 0; background: #fafafa; border-radius: 4px; }}
.issue.critical {{ border-left-color: #e53e3e; background: #fff5f5; }}
.issue.warning {{ border-left-color: #dd6b20; background: #fffaf0; }}
.issue.info {{ border-left-color: #3182ce; background: #f0f7ff; }}
.issue h3 {{ margin: 0 0 0.5rem 0; }}
.sev-tag {{ font-size: 0.75rem; padding: 0.15rem 0.4rem; border-radius: 3px; color: white; }}
.sev-tag.critical {{ background: #e53e3e; }}
.sev-tag.warning {{ background: #dd6b20; }}
.sev-tag.info {{ background: #3182ce; }}
.sev-tag.suggestion {{ background: #718096; }}
ul {{ padding-left: 1.5rem; }}
li {{ margin: 0.3rem 0; }}
@media print {{ body {{ padding: 1rem; }} .issue {{ break-inside: avoid; }} }}
</style>
</head>
<body>
<h1>AI Code Review Report</h1>
<div class="meta">
    <p><strong>PR:</strong> {title} &mdash; <strong>Author:</strong> {author}</p>
    <p><strong>Reviewed:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M')}</p>
</div>
<div class="score"><span>Score: {report.overall_score}/10</span></div>
<h2>Summary</h2>
<p>{report.summary}</p>
<h2>Issues ({len(report.issues)})</h2>
{issues_html or '<p>No issues found.</p>'}
<h2>Strengths</h2>
<ul>{strengths}</ul>
<h2>Suggestions</h2>
<ul>{suggestions}</ul>
<hr>
<p style="color:#999;font-size:0.8rem;">Generated by AI PR Reviewer (DeepSeek)</p>
</body>
</html>"""
